DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS VolunteerWork;
DROP TABLE IF EXISTS Ad;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Rating;
DROP TABLE IF EXISTS Shelter;
DROP TABLE IF EXISTS Event;